### ISSUE TITLE
npm install breaks

### ISSUE THREAD

**Issue by Chuseuiti** [bigchaindb/js-bigchaindb-driver#114]
If I download the source code and run:

`npm install `

It crashes during installation, any thoughts about why ? I think that npm is eating all the memory, however if I directly:

`npm install bigchaindb-driver `
(version 0.3.0)
Then is fine...

Log error:
```

npm http request GET https://registry.npmjs.org/is-fullwidth-code-point
npm http 304 https://registry.npmjs.org/is-fullwidth-code-point
npm info attempt registry request try #1 at 8:08:57 PM
npm http request GET https://registry.npmjs.org/lcid
npm info attempt registry request try #1 at 8:08:57 PM
npm http request GET https://registry.npmjs.org/mem
npm http 304 https://registry.npmjs.org/lcid
npm http 304 https://registry.npmjs.org/mem
npm info attempt registry request try #1 at 8:08:57 PM
npm http request GET https://registry.npmjs.org/invert-kv
npm http 304 https://registry.npmjs.org/invert-kv
npm info lifecycle bigchaindb-driver@0.3.0~preinstall: bigchaindb-driver@0.3.0
Killed         ....] - extract:moo-server: sill gunzTarPerm extractEntry lolex.js


```

Btw if I install them one by one, it does not run out of memory but it is not able to install the following dependencies:
```
bigchaindb-driver@0.3.0 /
+-- UNMET PEER DEPENDENCY babel-eslint@8.0.0
+-- UNMET PEER DEPENDENCY eslint@4.1.1
`-- UNMET PEER DEPENDENCY webpack@3.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN babel-loader@7.0.0 requires a peer of webpack@2 but none was installed.
npm WARN eslint-config-airbnb-base@11.3.2 requires a peer of eslint@^3.19.0 || ^4.5.0 but none was installed.
npm WARN eslint-config-airbnb-base@11.3.2 requires a peer of eslint-plugin-import@^2.7.0 but none was installed.
npm WARN eslint-config-ascribe@3.0.4 requires a peer of babel-eslint@^7.1.1 but none was installed.
npm WARN eslint-plugin-import@2.2.0 requires a peer of eslint@2.x - 3.x but none was installed.
```

**Comment by michielmulders** [comment]
I think this has nothing to do with the js-driver on npm, but with your npm installation itself. Have you tried clearing your cache, it's a common issue when getting 304's? 

´´´
npm cache clean
´´´´

**Comment by Chuseuiti** [comment]
The problem neither seems to be the 304 neither the memory. 

npm info retry fetch attempt 1 at 5:47:42 PM
npm info attempt registry request try #1 at 5:47:42 PM
npm http fetch GET https://registry.npmjs.org/when/-/when-3.7.8.tgz
npm info retry fetch attempt 1 at 5:47:42 PM
npm info attempt registry request try #1 at 5:47:43 PM
npm http fetch GET https://registry.npmjs.org/github/-/github-9.2.0.tgz
npm http fetch 200 https://registry.npmjs.org/when/-/when-3.7.8.tgz
npm http fetch 200 https://registry.npmjs.org/github/-/github-9.2.0.tgz
Killed   ..........] | fetchMetadata: http fetch 200 https://registry.npmjs.org/gi


So Im wondering is there any different between doing:

```
npm pack bigchaind-driver
tar -xvf bigchaindb-driver-0.3.0.tgz
cd package
npm install 
```

and 

`npm install bigchaindb-driver`

@michielmulders

**Comment by Chuseuiti** [comment]
@michielmulders  finally found that the error is with the development packages..that is why is not building.. I have to go into more details to see why

**Comment by Chuseuiti** [comment]
@michielmulders I found that the difference is the --production flag. Btw is there any docker container with the environment to be able to work on developing on js-bigchaindb-driver ..as the development 
dependencies on Ubuntu 16 are giving ..fsevents error

**Comment by riyazpanarwala** [comment]
I am also facing issue while installing bigchaindb driver using  npm install bigchaindb-driver

**Comment by kremalicious** [comment]
Cleaning up issues, please reopen or create a new issue if you're still running into these problems.
