### ISSUE TITLE
ECONNRESET Socket hang up

### ISSUE THREAD

**Issue by danielrea** [bigchaindb/js-bigchaindb-driver#134]
Hello,
We appear to be having an issue posting to BigchainDB via IPDB while connected to cellular connection on a Raspberry Pi.

**Error**
`[ERROR] [815980KiB] { FetchError: request to https://test.ipdb.io/api/v1/statuses?transaction_id=52f21dd7e14a1707c36dfc1ac701d4ff523a2a7d7abc7ad26ef7cd7c49fb1beb failed, reason: socket hang up
    at ClientRequest.<anonymous> (/home/acorn/canpipe/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketOnEnd (_http_client.js:346:9)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  name: 'FetchError',
  message: 'request to https://test.ipdb.io/api/v1/statuses?transaction_id=52f21dd7e14a1707c36dfc1ac701d4ff523a2a7d7abc7ad26ef7cd7c49fb1beb failed, reason: socket hang up',
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET' }`

**Operating System and Name:** 
acorn@raspberrypi-B:~ $ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian

**Any details about your local setup that might be helpful in troubleshooting:**
Running a Node application using the Javascript Driver.
Connected via cellular network.
The Raspberry Pi is also not stationary so signal will not be consistent.

**Detailed steps to reproduce the bug.**
Posting transactions at rate around 30 seconds under cellular connection with LTE.

**Comment by ttmc** [comment]
When I visit the URL https://test.ipdb.io/api/v1/statuses?transaction_id=52f21dd7e14a1707c36dfc1ac701d4ff523a2a7d7abc7ad26ef7cd7c49fb1beb with my browser, I get back:

```json
{"status": "valid"}
```

You can get "socket hang up" if your machine never got the HTTP response, maybe because the connection got lost or dropped. I'll check how we're handling that.

**Comment by kremalicious** [comment]
Cleaning up issues, please reopen or create a new issue if you're still running into these problems.
