### ISSUE TITLE
JS bichaindb driver and Android

### ISSUE THREAD

**Issue by adonnini** [bigchaindb/js-bigchaindb-driver#164]
Hi,

I would like to try and use the JS bigchaindb driver in my Android app.

Do you know of anyone how has tried to do this?

If yes, could you please tell me how?

Thanks,

Alex Donnini

**Comment by manolodewiner** [comment]
Hi @adonnini please ask this kind of questions in our [Gitter channel](https://gitter.im/bigchaindb/js-bigchaindb-driver). I'll answer you there :)
