### ISSUE TITLE
Boiler Plate - message: "HTTP Error: Requested page not reachable", status: "500 INTERNAL SERVER ERROR", requestURI: "https://test.bigchaindb.com/api/v1/transactions?mode=commit"

### ISSUE THREAD

**Issue by arunKumaramarnath** [bigchaindb/js-bigchaindb-driver#167]
Getting the below error, when trying to run the boiler plate example (Use a pre-built image (browser only)).

message: "HTTP Error: Requested page not reachable"
​
requestURI: "https://test.bigchaindb.com/api/v1/transactions?mode=commit"
​
status: "500 INTERNAL SERVER ERROR"

**Comment by ttmc** [comment]
This is a known issue and we're working to resolve it ASAP. For some details, see the recent blog post https://blog.bigchaindb.com/latest-release-bigchaindb-2-0-alpha-2-49206c537b1

You can also try contacting the other nodes in the Testnet, at:

test2.bigchaindb.com
test3.bigchaindb.com
test4.bigchaindb.com
