### ISSUE TITLE
Add transaction creation and execution module to js-bigchaindb-driver

### ISSUE THREAD

**Issue by adonnini** [bigchaindb/js-bigchaindb-driver#170]
Hi,

I am running into problems trying to use the js-bigchaindb-driver from my Android java app. I found a way to run the driver using

https://github.com/janeasystems/nodejs-mobile

However, unfortunately, at this point in time nodejs-mobile supports only one node.js runtime environment execution at a time.

This means that I cannot run the driver, and then execute a bigchaindb transaction.

So, perhaps being too simplistic (or just wishful thinking), I was wondering if you think it might make sense for me to add a module to the driver  that basically replicates the code for creating and executing a specific transaction (as in you example in readme.md).

Is this just a stupid idea?

Any thoughts about this and how I could resolve the problem, would be greatly appreciated.

Thanks,

Alex Donnini

**Comment by ttmc** [comment]
I don't understand what you mean when you write, "then execute a bigchaindb transaction."

A bigchaindb transaction is a JSON string. One sends it over the wire to a bigchaindb network to be checked for validity and, if it's valid, stored in that network's blockchain.

**Comment by adonnini** [comment]
Sorry. I guess I did not explain myself clearly enough.

In READ.MD for the js-bigchaindb driver you have sample code for "Create a transaction".

Because at this point in time, nodejs-mobile supports only running one execution environment at a time, for the purpose of testing I was wondering if it might even make sense trying to add a module to the driver that suns the sample code at start-up. In Java, this could be easily accomplished by adding the sample "Create a transaction" code to onCreate() after start-up is completed.

I am not familiar with JS. I don't know if this is possible.

Does this better explain what I am trying to do? It's only for the purpose of testing.

Thanks,

Alex Donnini

**Comment by kremalicious** [comment]
You should be able to access each function individually anyway so js driver already does what you want I think:

```js
import Transaction from 'src/transaction.js'

Transaction.serializeTransactionIntoCanonicalString(YOUR_TRANSACTION)
```

Closing this for now, since there's really nothing we can do here. Feel free to reopen if you think that's an issue with the js driver.

**Comment by adonnini** [comment]
@kremalicious your are thinking JS, not Java. My app, and most Android apps, is Java based not JS.

In any event, I solved my problem in a different way.

Thanks,

Alex Donnini
