### ISSUE TITLE
Web view base error

### ISSUE THREAD

**Issue by harishdrish123** [bigchaindb/js-bigchaindb-driver#179]
Hi,

Issue with accessing transaction on web browser after installing server on local machine.

Here is the error log 
[2018-05-22 17:04:15] [ERROR] (bigchaindb.web.views.base) HTTP API error: 404 - GET:/api/v1/transactions/f78ed7deee65ec6818c25311b7a72a05173b69fb421100837422855c96e0b5d9 - Not found (webapi     - pid: 15199)

[bigchaindb-errors.log](https://github.com/bigchaindb/js-bigchaindb-driver/files/2026522/bigchaindb-errors.log)

**Comment by ttmc** [comment]
One possibility is that the transaction was never posted/sent to the server.

Another possibility is that the transaction was posted, but it was invalid, and therefore discarded.

We will need more information to know for sure what happened.

**Comment by harishdrish123** [comment]
Hi Thanks for response!!

First I have created transaction and it is showing created transaction on terminal, please find created transaction screenshot and code to create transaction.

But when I access same created transaction in the browser using this url : http://localhost:9984/api/v1/transactions/f78ed7deee65ec6818c25311b7a72a05173b69fb421100837422855c96e0b5d9
 showing 404 status as in the attached screenshot

![create-transaction](https://user-images.githubusercontent.com/36157904/40363315-c925cbca-5dec-11e8-9b77-88f41d4c6dba.png)
![not-found](https://user-images.githubusercontent.com/36157904/40363316-c969778a-5dec-11e8-9860-0c68837b7554.png)
[code.txt](https://github.com/bigchaindb/js-bigchaindb-driver/files/2026699/code.txt)

**Comment by manolodewiner** [comment]
I am afraid the transaction is not created as you are getting a 500 error.

**Comment by manolodewiner** [comment]
We can not really help you with that log. Please check which bigchaindb version you are running, which driver version, and try to see the logs of BigchainDB.

**Comment by manishverma01** [comment]
I really don't know what to do next, also find same issue I am facing https://github.com/bigchaindb/bigchaindb/issues/2225, but no solution.

**Comment by manishverma01** [comment]
The same code I used, working fine on testnet server but not on my local setup

**Comment by manolodewiner** [comment]
Can you please check your version of BigchainDB. Are you running BigchainDB using docker? This issue https://github.com/bigchaindb/bigchaindb/issues/2225 was happening for me while posting 60 tx per second. I don't think you have the same issue.
If your script is running properly on the test network and not on your local environment, then you are not running bigchaindb properly. Follow the documentation and update to the latest version of BigchainDB

**Comment by manishverma01** [comment]
Below is the screenshot showing the version and errors after the command bigchaindb start!!

Can you please check the errors in attached screenshot and suggest me solution for that 

![version](https://user-images.githubusercontent.com/39479940/40409158-91e2abb0-5e87-11e8-9eb0-dfe0aa30ecef.png)
![errors](https://user-images.githubusercontent.com/39479940/40409159-9222d29e-5e87-11e8-9426-659030fc777e.png)

**Comment by manishverma01** [comment]
Below is the server configuration, is there anything I am missing??

{
    "server": {
        "bind": "localhost:9984",
        "loglevel": "info",
        "workers": null
    },
    "wsserver": {
        "scheme": "ws",
        "host": "localhost",
        "port": 9985,
        "advertised_scheme": "ws",
        "advertised_host": "localhost",
        "advertised_port": 9985
    },
    "database": {
        "backend": "localmongodb",
        "connection_timeout": 5000,
        "max_tries": 3,
        "ssl": false,
        "ca_cert": null,
        "certfile": null,
        "keyfile": null,
        "keyfile_passphrase": null,
        "crlfile": null,
        "host": "localhost",
        "port": 27017,
        "name": "bigchain",
		"replicaset": null,
        "login": null,
        "password": null
    },
    "keypair": {
        "public": null,
        "private": null
    },
    "keyring": [],
    "backlog_reassign_delay": 120,
    "log": {
        "file": "/home/bigchain/bigchaindb.log",
        "error_file": "/home/bigchain/bigchaindb-errors.log",
        "level_console": "info",
        "level_logfile": "info",
        "datefmt_console": "%Y-%m-%d %H:%M:%S",
        "datefmt_logfile": "%Y-%m-%d %H:%M:%S",
        "fmt_console": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "fmt_logfile": "[%(asctime)s] [%(levelname)s] (%(name)s) %(message)s (%(processName)-10s - pid: %(process)d)",
        "granular_levels": {},
        "port": 9020
    },
    "CONFIGURED": true
}
