### ISSUE TITLE
OpenSSL error install

### ISSUE THREAD

**Issue by lucaspojo** [bigchaindb/js-bigchaindb-driver#187]
Hi, i try to insall bigchaindb driver, but i have an error : 

LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib'

Windows 10 64B

How to fix ? Thx !

**Comment by ttmc** [comment]
Maybe you need to install OpenSSL on your Windows 10 machine. To get it, go to:

http://slproweb.com/products/Win32OpenSSL.html

**Comment by ttmc** [comment]
I guess you need to install a 64-bit version of OpenSSL on your Windows machine. See https://wiki.openssl.org/index.php/Binaries

**Comment by lucaspojo** [comment]
Thx for reply, i have install OpenSSL ia get the same error : 

> rs\lucaspojo\Documents\GitHub\bcd-test\node_modules\ed25519\build\ed25519.vcxproj]
..\src\ed25519\sc_muladd.c(366): warning C4244: '=': conversion from 'crypto_int64' to 'unsigned char', possible loss of data [C:\Use
rs\lucaspojo\Documents\GitHub\bcd-test\node_modules\ed25519\build\ed25519.vcxproj]
..\src\ed25519\sc_muladd.c(367): warning C4244: '=': conversion from 'crypto_int64' to 'unsigned char', possible loss of data [C:\Use
rs\lucaspojo\Documents\GitHub\bcd-test\node_modules\ed25519\build\ed25519.vcxproj]
  ed25519.cc
  win_delay_load_hook.cc
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\Users\lucaspojo\Documents\GitHub\bcd-test\
node_modules\ed25519\build\ed25519.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lucaspojo\Documents\GitHub\bcd-test\node_modules\ed25519
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\lucaspojo\Documents\GitHub\bcd-test\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\lucaspojo\Documents\GitHub\bcd-test\package.json'
npm WARN bcd-test No description
npm WARN bcd-test No repository field.
npm WARN bcd-test No README data
npm WARN bcd-test No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ed25519@0.0.4 (node_modules\ed25519):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ed25519@0.0.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ bigchaindb-driver@4.0.1
updated 1 package in 15.602s

**Comment by lucaspojo** [comment]
Fixed !

After install OpenSSL 64B with the previous link, download and put this file in lib folder : 
https://github.com/ReadyTalk/win32/blob/master/msvc/lib/libeay32.lib
