### ISSUE TITLE
Installation problem zlib: unexpected end of file

### ISSUE THREAD

**Issue by fernandosainzafkar** [bigchaindb/js-bigchaindb-driver#188]
I'm unable to install the module. OS is MacOs High Sierra, node version is 8.11.1, npm version is 6.0.0.
npm install bigchaindb-driver
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:

Log file:
info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'bigchaindb-driver' ]
2 info using npm@6.0.0
3 info using node@v8.11.1
4 verbose config Skipping project config: /Users/myuser/.npmrc. (matches userconfig)
5 verbose npm-session 7de94220a1ea6364
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 200 https://registry.npmjs.org/bigchaindb-driver 17ms (from cache)
9 http fetch GET 200 https://registry.npmjs.org/bigchaindb-driver/-/bigchaindb-driver-4.0.1.tgz 272ms (from cache)
10 silly fetchPackageMetaData error for bigchaindb-driver@latest zlib: unexpected end of file
11 timing stage:rollbackFailedOptional Completed in 2ms
12 timing stage:runTopLevelLifecycles Completed in 698ms
13 verbose stack ZlibError: zlib: unexpected end of file
13 verbose stack     at Zlib.(anonymous function).onerror (/usr/local/lib/node_modules/npm/node_modules/tar/node_m$
13 verbose stack     at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.$
13 verbose stack     at Unzip.flush (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.$
13 verbose stack     at Unzip.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js$
13 verbose stack     at Object.end (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:415:21)
13 verbose stack     at PassThrough.onend (_stream_readable.js:595:10)
13 verbose stack     at Object.onceWrapper (events.js:313:30)
13 verbose stack     at emitNone (events.js:111:20)
13 verbose stack     at PassThrough.emit (events.js:208:7)
13 verbose stack     at endReadableNT (_stream_readable.js:1064:12)
13 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
13 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
14 verbose cwd /Users/myuser
15 verbose Darwin 17.5.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bigchaindb-driver"
17 verbose node v8.11.1
18 verbose npm  v6.0.0
19 error code Z_BUF_ERROR
20 error errno -5
21 error zlib: unexpected end of file
22 verbose exit [ -5, true ]

Thanks.

**Comment by kremalicious** [comment]
using the same environment I can't reproduce this error. Are you still having this problem?

**Comment by frknasir** [comment]
try this `npm cache clean --force`

**Comment by siqueiradg** [comment]
`npm cache clean --force` worked for me. Thanks.

**Comment by frknasir** [comment]
You are welcome.

**Comment by kplvashisahat** [comment]
I am facing this same problem, I am using win10 , I ran these commands but didn't get something:-
- npm remove nativescript -g
- npm cache clear --force 
- npm install nativescript -g

**Comment by kremalicious** [comment]
@kplvashisahat I doubt you face the same problem, you probably wanna go here https://github.com/NativeScript/nativescript-cli

**Comment by obendesmond** [comment]
I am facing this same problem, but using ubuntu 18.04 and 
"npm cache clean --force" didn't work for me.
Need help please

**Comment by josera21** [comment]
I have the same issue that @obendesmond  on Debian stretch

**Comment by SOWMITHRACHINNADURAI** [comment]
npm cache clean --force worked for me. Thanks.

**Comment by pal259** [comment]
npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
[..................] | : WARN using --force I sure hope you know what you are doing.



its stop ....cant run above command

**Comment by mallikvarma** [comment]
I am having the same issue, anyone found the solution ?

**Comment by nguyenrio18** [comment]
test

**Comment by MuhammadBilalYar** [comment]
Same issue

**Comment by lycan333** [comment]
> try this `npm cache clean --force`

for me too worked thanks

**Comment by brandon-kyle-bailey** [comment]
win10 here, `npm cache clean --force` worked for me.

**Comment by aviranmz** [comment]
npm cache clean --force
worked for me also
