### ISSUE TITLE
test.bigchaindb.com not working when pushing transaction

### ISSUE THREAD

**Issue by dvalencia-sd** [bigchaindb/js-bigchaindb-driver#260]
It says Network request failed.

Any thoughts?

**Comment by ttmc** [comment]
The new BigchainDB test network at test.bigchaindb.com doesn't require the `app_id` or `app_key` HTTP request headers, and in fact it won't accept them, so just remove them (i.e. don't include them) from your HTTP requests to the new BigchainDB test network.

I'm updating the website and docs to reflect this change.
