### ISSUE TITLE
example code doesn't work against IPDB

### ISSUE THREAD

**Issue by kremalicious** [bigchaindb/js-bigchaindb-driver#28]
Tossing this here, not clear if js driver problem or specific IPDB problem. Just following the usage example with added authentication, API returns a `400 BAD REQUEST`. Which sounds like the transaction is not generated correctly

<details>
 <summary>Node.js example code</summary>

```js
const driver = require('bigchaindb-driver')

const API_PATH = 'https://test.ipdb.io/api/v1/'
const APP_ID = '...'
const APP_KEY = '...'

const alice = new driver.Ed25519Keypair()

const tx = driver.Transaction.makeCreateTransaction(
    { assetMessage: 'My very own asset...' },
    { metaDataMessage: 'wrapped in a transaction' },
    [ driver.Transaction.makeOutput(
            driver.Transaction.makeEd25519Condition(alice.publicKey))
    ],
    alice.publicKey
)

const txSigned = driver.Transaction.signTransaction(tx, alice.privateKey)

let conn = new driver.Connection(API_PATH, { 
    'Content-Type': 'application/json',
    app_id: APP_ID,
    app_key: APP_KEY
})

conn.postTransaction(txSigned)
    .then(() => conn.getStatus(txSigned.id))
    .then((res) => console.log('Transaction status:', res.status))
```

</details>

**Comment by ttmc** [comment]
Here's an idea that might help you figure out why you're getting `400 Bad Request`:

1. Create a RequestBin at https://requestb.in/
2. In the Node.js example code, replace the URL in `API_PATH` with the URL of your new RequestBin
3. Run the Node.js code
4. Go to your RequestBin and visually inspect all elements of the HTTP request. Is something obviously wrong?

**Comment by kremalicious** [comment]
nice tool, but doesn't work cause driver auto-addds `/transactions` at the end. 

Already logging the signed transaction, anything suspicious in there?:

<details>
  <summary>console.log(txSigned)</summary>

```
{ id: '106cda34f6a8252e97c88119c1e1b752ca479759efd0fcb38075c35bf3acb824',
  operation: 'CREATE',
  outputs: [ { amount: '1', condition: [Object], public_keys: [Array] } ],
  inputs: 
   [ { fulfillment: 'cf:4:QVM4zgFisR3x30lZkGGbtX_MW7TihXz_FQO4hUpNidgTgBWy6tw_PTy3RtXJl-LiPp6Fe9IcrQm5H2OcqqIrqL_rGp14q5ajBuqRx67TwNhucFD4TJLz3rRr-Zm_sBUD',
       fulfills: null,
       owners_before: [Array] } ],
  metadata: { metaDataMessage: 'wrapped in a transaction' },
  asset: { data: { assetMessage: 'My very own asset...' } },
  version: '0.9' }
```

</details>


Driver seems to spit out some sort of response in the console all the time, not sure it should do that:

<details>
  <summary>driver console response</summary>

```
Body {
  url: 'https://test.ipdb.io/api/v1/transactions',
  status: 400,
  statusText: 'BAD REQUEST',
  headers: 
   Headers {
     _headers: 
      { server: [Array],
        date: [Array],
        'content-type': [Array],
        'content-length': [Array],
        connection: [Array] } },
  ok: false,
  body: 
   PassThrough {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 94,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: false,
        endEmitted: false,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: true,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        prefinish: [Object],
        unpipe: [Function: onunpipe],
        drain: [Function],
        error: [Function: onerror],
        close: [Object],
        finish: [Object] },
     _eventsCount: 7,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 1,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     _transformState: 
      TransformState {
        afterTransform: [Function],
        needTransform: true,
        transforming: false,
        writecb: null,
        writechunk: null,
        writeencoding: 'buffer' } },
  bodyUsed: false,
  size: 0,
  timeout: 0,
  _raw: [],
  _abort: false }
```
</details>

**Comment by krish7919** [comment]
> { id: '106cda34f6a8252e97c88119c1e1b752ca479759efd0fcb38075c35bf3acb824',
  operation: 'CREATE',
  outputs: [ { amount: '1', condition: [Object], public_keys: [Array] } ],
  inputs: 
   [ { fulfillment: 'cf:4:QVM4zgFisR3x30lZkGGbtX_MW7TihXz_FQO4hUpNidgTgBWy6tw_PTy3RtXJl-LiPp6Fe9IcrQm5H2OcqqIrqL_rGp14q5ajBuqRx67TwNhucFD4TJLz3rRr-Zm_sBUD',
       fulfills: null,
       owners_before: [Array] } ],
  metadata: { metaDataMessage: 'wrapped in a transaction' },
  asset: { data: { assetMessage: 'My very own asset...' } },
  version: '0.9' }

Try with `amount` as an `int`.

**Comment by krish7919** [comment]
@kremalicious I observed an error on the testnet: `HTTP API error: 400 - Invalid transaction schema: '1' is not of type 'integer'`

**Comment by kremalicious** [comment]
Cool, thanks for the investigation, more bugs rendering the driver unusable. It seems nobody has ever tested it. I just use the driver, I didn't write the code and my nudging towards writing tests to catch stuff like this failed so far https://github.com/bigchaindb/js-bigchaindb-driver/pull/16

**Comment by ttmc** [comment]
There are many changes happening to the transaction model between BigchainDB Server 0.10.2 and 1.0. You already noticed that "amount" changed from a number to a string. Another one is that signatures are calculated differently. And there are more... The IPDB Test Network is running 0.10.2 so you need a JavaScript driver that can write transactions that were valid for 0.10.2. I didn't write the JavaScript driver either. You should ask someone who did.

**Comment by kremalicious** [comment]
Well we clearly say, driver is compatible with v0.10.1:
<img width="430" alt="screen shot 2017-06-15 at 10 15 11" src="https://user-images.githubusercontent.com/90316/27171943-a87e21ec-51b3-11e7-961b-31b9e5b0133f.png">

looks like @TimDaub added this compatibility matrix https://github.com/bigchaindb/js-bigchaindb-driver/commit/4e8087ee0e005c9252429730ade03488e6342b5e so @TimDaub, were you every able to create a transaction with this driver?

**Comment by TimDaub** [comment]
You're a bunch of funny people :D https://github.com/bigchaindb/js-bigchaindb-driver/commit/61b5cc8c90580812a5ee3b770d418da1e99a3c03#diff-04c6e90faac2675aa89e2176d2eec7d8L14

Try with 0.1.x

**Comment by kremalicious** [comment]
nothing in the internals of the driver changed between `0.1.x` and `1.0.x`

**Comment by kremalicious** [comment]
ok, so looks like this driver is completely broken due to merging of some PRs intended to get the driver compatible with some future BigchainDB version. For whatever reason those changes are now in `master` instead of a development branch. This has never been communicated in the PRs or to me. So, now we have a broken driver for the next weeks or months, yet we tell users to use this driver on both, BigchainDB & IPDB web properties

**Comment by kremalicious** [comment]
so we were able to actually create a [transaction](https://test.ipdb.io/api/v1/transactions/194db348c37cc088a8ce4e32c108155241536e7df8d9e69598969b36240c8c52) with this thing in the [`ipdb-compatibility`](https://github.com/bigchaindb/js-bigchaindb-driver/tree/ipdb-compatiblity) branch (whoop, whoop). 

But `.then(() => conn.getStatus(txSigned.id))` still returns a `400`

**Comment by kremalicious** [comment]
with the newly published package (thx @vrde) I still get `status: 400, statusText: 'BAD REQUEST'`. Are we tracking this bug somewhere?

**Comment by TimDaub** [comment]
> with the newly published package (thx @vrde) I still get status: 400, statusText: 'BAD REQUEST'. Are we tracking this bug somewhere?

Just created #38

**Comment by kremalicious** [comment]
Thanks Tim, closing this since remaining issue is isolated now
