### ISSUE TITLE
Asset amount coerced to string in transaction.makeOutput

### ISSUE THREAD

**Issue by deweller** [bigchaindb/js-bigchaindb-driver#34]
When I try to use transaction.makeOutput with a second parameter of 1000, I get the following error from https://test.ipdb.io/api/v1/:

```json
{
  "message": "Invalid transaction schema: '1000' is not of type 'integer'",
  "status": 400
}
```

The makeOutput method coerces the amount to a string, but it appears that ipdb is expecting an integer.

Which one has the correct schema?  The client or the server?

**Comment by TimDaub** [comment]
Hey @deweller, thanks for reporting.

We're aware of the issue, a few incorrect versions were released.
We're trying to fix the problem today in #33. @vrde will let you know when the problem was resolved.

Sorry for any inconveniences.

**Comment by vrde** [comment]
Hi @deweller, I've just cleaned [`bigchaindb-driver`](https://www.npmjs.com/package/bigchaindb-driver). I did some bad things like unpublishing old releases, but they weren't working anyway.

I tested `bigchaindb-driver v0.1.0` on `node v7.8.0` and it works fine. Can you install `bigchaindb-driver v0.1.0` and tell me if it works? (I assume you are on node, not on the browser). Thanks :crossed_fingers:

**Comment by TimDaub** [comment]
@deweller I'm closing this issue now.

If you ever have problems with this, please let me know and we can reopen.
