### ISSUE TITLE
getStatus returns 400 with IPDB

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/js-bigchaindb-driver#38]
For more info see this thread: https://github.com/bigchaindb/js-bigchaindb-driver/issues/28#issuecomment-309396056

It's still to be determined if this is a IPDB or js-driver related bug

**Comment by kremalicious** [comment]
just a heads up: when using the release js driver against `diminet.bigchaindb.com` I get a `400` too. So I think we can rule out IPDB then

**Comment by kremalicious** [comment]
But IPDB is actually more helpful in the response, nice:

diminet returns: `The browser (or proxy) sent a request that this server could not understand.`
IPDB returns: `Invalid transaction schema: '1' is not of type 'integer'`

**Comment by TimDaub** [comment]
This is a BigchainDB server problem.

We'll handle here: https://github.com/bigchaindb/bigchaindb/issues/1576
