### ISSUE TITLE
Test coverage ≥95%

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/js-bigchaindb-driver#4]
For files that still lack code coverage, here is an overview: https://codecov.io/gh/bigchaindb/js-bigchaindb-driver

**Comment by innoprenuer** [comment]
This issue will be bountied on Gitcoin. Another issue has been created for this purpose in this repo. For more details refer [https://github.com/bigchaindb/js-bigchaindb-driver/issues/220](https://github.com/bigchaindb/js-bigchaindb-driver/issues/220)
