### ISSUE TITLE
makeTransferTransaction can take multiple transactions as inputs

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/js-bigchaindb-driver#44]
BigchainDB supports multiple inputs and outputs in TRANSFER transactions and multiple outputs in a CREATE transaction.

`makeTransferTransaction`  however, currently doesn't allow a user to pass multiple inputs.

For more documentation on how this works, you may want to take a look at existing documentation:

- https://docs.bigchaindb.com/projects/server/en/latest/data-models/inputs-outputs.html
- https://docs.bigchaindb.com/projects/server/en/latest/data-models/transaction-model.html
- https://docs.bigchaindb.com/projects/py-driver/en/latest/advanced-usage.html#multiple-owners
- as well as this method (it's implementation/interface is to some not ideal, so maybe don't take too much from there): https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/common/transaction.py#L590

**Comment by iredjee** [comment]
Hi, any progress on this task?

**Comment by manolodewiner** [comment]
We can close this issue, as this is already supported in the 3.2 version of the driver. See https://github.com/bigchaindb/js-bigchaindb-driver/pull/125
