### ISSUE TITLE
When releasing to npm, clean dist folder such that `bundle.*` do not get published

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/js-bigchaindb-driver#66]
See this link: https://unpkg.com/bigchaindb-driver@0.1.2/dist/browser/
https://unpkg.com/bigchaindb-driver@0.3.0/dist/browser/

The only working bundles are `bigchaindb-driver.*`. Remove all `bundle...`

**Comment by michielmulders** [comment]
@TimDaub I executed `npm run build` to build the bundles but got this as a result:
```
bigchaindb-driver.amd.min.js       
bigchaindb-driver.cjs.min.js.map
bigchaindb-driver.amd.min.js.map   
bigchaindb-driver.umd.min.js
bigchaindb-driver.cjs2.min.js     
bigchaindb-driver.umd.min.js.map
bigchaindb-driver.cjs2.min.js.map  
bigchaindb-driver.window.min.js
bigchaindb-driver.cjs.min.js       
bigchaindb-driver.window.min.js.map
```

So no bundle.* are being built in dist/browser. Correct?

**Comment by TimDaub** [comment]
Yup. It may be that this issue was already solved and the person pushing to npm (me) should clean his dist folder? I'll check later and close if that's the case.
