### ISSUE TITLE
Create sphinx style docs for JS-driver and reconcile with Python docs

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/js-bigchaindb-driver#79]
As a guide line see docs for BDB-PY-driver: https://docs.bigchaindb.com/projects/py-driver/en/latest/index.html

We do not necessarily want all of that content. What I think would be important however is:

- Installation guide for npm and browsers (current readme.md): Quickstart
- [Determine the BigchainDB Root URL](https://docs.bigchaindb.com/projects/py-driver/en/latest/connect.html): reconcile with Python driver; maybe move this page to server docs? /cc @ttmc
- [Basic Usage Examples](https://docs.bigchaindb.com/projects/py-driver/en/latest/usage.html): Should be the main focus
- [Advanced Usage Examples](https://docs.bigchaindb.com/projects/py-driver/en/latest/advanced-usage.html): needs #44 first, for Cryptoconditions only docs for Ed25519, multiple inputs and outputs and sha256thresholds

That's all for a first cut.

**Comment by michielmulders** [comment]
@TimDaub I recommend moving BigchainDB Root URL to server docs. I would add it to the [quickstart](https://docs.bigchaindb.com/projects/server/en/latest/quickstart.html): The documentation tells how to set it up, but doesn't give information about verifying to proper installation of a single stand-alone BigchainDB node. Could possibly add:

J. Verify functioning of BigchainDB Server (if you didn't change root url) by surfing to following url: **http://127.0.0.1:9984/**

This should return an object containing information about api, docs, BDB version and your public key.

**Comment by ttmc** [comment]
See https://github.com/bigchaindb/bigchaindb/pull/1687

**Comment by manolodewiner** [comment]
I think we can already close this issue
