### ISSUE TITLE
Document supplying credentials

### ISSUE THREAD

**Issue by addywaddy** [bigchaindb/js-bigchaindb-driver#80]
It's only a small thing but I had to look at the python implementation and `connection/index.js` to realise that `Connection` takes an optional second argument for supplying credentials as an object. Would be great if this could be documented as well.

**Comment by TimDaub** [comment]
Absolutely right. We'll be setting up docs for the driver soon.
In the mean time, headers can be passed to a connection like this:

```js
const driver = require('bigchaindb-driver')
let bdb = new driver.Connection('bigchaindbURL', { 
    abc: '123',
})
```

**Comment by TimDaub** [comment]
This is now documented here: https://docs.bigchaindb.com/projects/js-driver/en/latest/usage.html#create-connection-with-bigchaindb
