### ISSUE TITLE
This repo is undiscoverable and confusing

### ISSUE THREAD

**Issue by kremalicious** [bigchaindb/js-bigchaindb-driver#9]
Questions completely unanswered in the Readme:

1. Is this an official client?
2. Is this written for Node.js?
3. Why is npm package name not just `bigchaindb`?

As [mentioned here](https://github.com/bigchaindb/bigchaindb/issues/256#issuecomment-302042138), Node.js devs won't be able to find this repository although they're the main target group for this repo.

**Comment by TimDaub** [comment]
@kremalicious:

For efficiency: What are actionables we can complete to address your concerns?

I can think of a few things:

- dedicated driver and bdb download page
- linking from the bdb root docs to driver docs and repo
- having sphinx style docs for this driver
- link from sohkai's driver to this driver
- whatelse?

**Comment by kremalicious** [comment]
- mention "official driver" in readme & repo description
- mention `Node.js` in the readme prominently, also in repo description
- use `nodejs` in the repo name (cause JavaScript & Node.js are not synonym. Or am I getting old and the kids these days expect that already?)
- change npm package name to `bigchaindb` (at least no need to mention language, `bigchaindb-driver` if we absolutely need distinction from actual server)

Linking from docs was done earlier today: https://github.com/bigchaindb/bigchaindb/pull/1481

Started planning a Get Started page ([Trello card](https://trello.com/c/Or2ViAEF/38-get-started-page)) where all the important first steps are consolidated, including linking up the official drivers so this would cover your first point. Agree this is the one with most impact, will help in boosting this repo in search results.

Apart from that and more in general, consistently naming our drivers would help too, as outlined in https://github.com/bigchaindb/org/issues/35

**Comment by kremalicious** [comment]
most of the stuff in here has been addressed in #11 and externally
