### ISSUE TITLE
For empty return set, listTransactions is not returning a list

### ISSUE THREAD

**Issue by TimDaub** [bigchaindb/js-bigchaindb-driver#96]
Try on IPDB test net

`conn.listTransaction('e77ab9036f4ae5c276502f02c825a8c03349ee1d8be139a44d0cb6ae7a8852f2', 'TRANSFER')`

Transaction exists and was never spent. Instead of returning an empty array it's returning some weird internal object:

```{"": 3, _state: undefined, _result: undefined, _subscribers: Array(0)}```

**Comment by michielmulders** [comment]
Hi Tim, I tested this and it worked perfectly for me:

```
const driver = require('bigchaindb-driver')

// BigchainDB server instance or IPDB (e.g. https://test.ipdb.io/api/v1/)
const API_PATH = 'https://test.ipdb.io/api/v1/'

// Send the transaction off to BigchainDB
const conn = new driver.Connection(API_PATH, { 
    app_id: 'my_id',
    app_key: 'my_key'
})

conn.listTransactions('e77ab9036f4ae5c276502f02c825a8c03349ee1d8be139a44d0cb6ae7a8852f2', 'TRANSFER')
    .then(res => console.log(res))
```

Response: `[ ]`

@TimDaub is it possible that you misspelled the function name? It should be conn.listTransaction**s** ?

**Comment by manolodewiner** [comment]
I also tested and I get the same response as @michielmulders 
https://jsfiddle.net/rdefk3hq/
Can we close this issue then?
